// AngularTuts/services-app/src/app/deposit-calculator/deposit-calculator.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-deposit-calculator',
  imports: [],
  templateUrl: './deposit-calculator.component.html',
  styleUrl: './deposit-calculator.component.css'
})
export class DepositCalculatorComponent {
  maturityAmount: number = 0;
  getMaturity(): number{
    return this.maturityAmount;
  }
  calculateMaturity(principalValue: string, tenureValue: string): void {
    const principal = parseFloat(principalValue);
    const tenure = parseInt(tenureValue);
    let interestRate = 7 / 100; 
    console.log("Calculating Maturity");
    if (isNaN(principal) || principal <= 0) {
        alert("Please enter a valid principal amount.");
        return;
    }
    if (isNaN(tenure) || tenure < 1 || tenure > 10) {
        alert("Please enter a valid tenure between 1 and 10 years.");
        return;
    }
    this.maturityAmount = principal * Math.pow(1 + interestRate, tenure);
  }
}

<div>
    <h1>Deposit Calculator</h1>
    Principal: <input  #principal type="number" value="1000"><br>
    Tenure: <input #tenure  type="number" value="5"><br>
    Interest Rate: <input type="text" id="interestRate" value="7%" readonly><br>
    Maturity: <input type="number" id="maturity" [value]="getMaturity()" readonly><br><br>
    <button (click)="calculateMaturity(principal.value, tenure.value)"> Calculate</button>
</div>

// React_Tutorials/bankcalculator/src/DepositCalculator.js
import { useState } from "react";

function DepositCalculator(){
    const [principal , setPrincipal] = useState("");
    const [tenure, setTenure] = useState("");
    const [maturity, setMaturity] = useState("");

    function calculateMaturity(){
        console.log(principal);
        if (!principal){
            alert("Please enter the principal amount");
        }
        else if (!tenure){
            alert("Please enter the tenure");
        }
        else{
            const interest = 7;
            const maturity = principal * Math.pow((1 + interest/100), tenure);
            setMaturity(maturity);
        }
    }
    return(
        <>
        <div>
            <h1>Deposit Calculator</h1>
            Principal: <input type="number" onChange={(e) => {
                if (e.target.value === ""){
                    setPrincipal("");
                }
                else{
                    setPrincipal(e.target.valueAsNumber);
                }
            }}/><br/>
            Tenure: <input type="number" onChange={(e) =>{
                if (e.target.valueAsNumber > 0 && e.target.valueAsNumber <= 30) {
                    setTenure(e.target.valueAsNumber);
                }
                else{
                    alert("Please enter a valid tenure");
                }
            }}/><br/>
            Interest Rate: <input readonly value={"7%"}/><br/>
            Maturity: <input readOnly value={maturity}/><br/><br/>
            <button onClick={calculateMaturity}>Calculate</button>
        </div>
        </>
    );
}

export default DepositCalculator;
